### ISSUE TITLE
文档代码块上色不会预先加载

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#12]
当运行程序后直接进入文档模块时，可能出现代码块没有上色或者上色错误的现象。初步分析其原因为上色相关的模块仅仅在编辑器启动后才会加载。应该在不影响程序运行的前提下适当调整这些模块的加载顺序。

联系一下#3 中的问题，能否一起解决？@jjyyxx

**Comment by jjyyxx** [comment]
原因是没有设置theme。修复于 9462aa4
