### ISSUE TITLE
增加编辑器输入时播放输入音符的功能

### ISSUE THREAD

**Issue by NN708** [obstudio/Thulium-Music-3#14]
大多数软件有输入时播放出输入音符的功能，可以考虑在编辑器中加入该功能：

1. 输入 1-7 各音符时播放该音符；
2. 输入音高操作符或和弦记号时播放修改后的音符；
3. 和弦各音符输入时播放输入的单音符，和弦括号闭合时播放该和弦。

**Comment by shigma** [comment]
不建议。如果以后我们做五线谱编辑可以加入，但是我不认为这种功能适合文本编写。有以下的原因：
1. 一般的打谱软件的输入方式是选取音符后点击对应的音高（五线谱的线和间），这样只会出现一个声音，的确对编曲有利。但是我们的编辑涉及很复杂的情况，输入时可能产生非常多的音，这并不是一种很好的体验。而且在另一些时候（比如编辑模板音轨和打击乐音轨时）用户反倒不希望听见这些没有意义的音符。
2. 文本编辑的一大优点是其远高于打谱软件的效率性。我们往往是以很快的速度打完一个或数个小节才希望听到音乐。现在上线的音轨和乐章单独播放功能已经能够很好地适应这一点了，没有必要额外加入这个功能。

**Comment by NN708** [comment]
那后期再考虑吧
