### ISSUE TITLE
Simple 主题制作

### ISSUE THREAD

**Issue by jjyyxx** [obstudio/Thulium-Music-3#15]
目前dark主题相对完整，但主要模仿Github风格的simple主题存在有很多瑕疵，需要进行优化。

**Comment by shigma** [comment]
@NN708 刚刚看到了 d64303b 的更新，做的很棒，再补充几点：
1. 文字主色调（#24292e）感觉不够深，希望能够稍微加深一些。
2. 表格部分按纵列上色时，希望整体再调整一下。个人的观点是中间比两边浅会更好一些。
3. 希望能够补全编辑器的配色方案。

**Comment by NN708** [comment]
@Shigma 文字主色调是按 GitHub 上调的。我自己调的过程中也感觉黑色这边到了深色颜色差距是不太看得出来的，需要留一点余地。如果你觉得不够深的话，你可以试试看改一下，看哪个颜色比较合适。

**Comment by shigma** [comment]
@NN708 个人感觉颜色变成原来的 0.6 倍左右比较合适。

**Comment by shigma** [comment]
有关 d647bd8 的一点点建议：
1. 当前所在行的背景色是黑色，这个是忘记调了？
2. 选中部分的背景色建议改成蓝色，参考 GitHub Plus 主题。

话说回来，`Microsoft VS Code\resources\app\extensions\theme-xxx\themes\yyy.json`里面有配色的信息，你可以直接复制到 yaml 文件里啊？

**Comment by NN708** [comment]
@Shigma d647bd8 中 YAML 里的还没改，只是先做了 CSS

**Comment by NN708** [comment]
Simple 主题已基本完成，大家看看还有什么要修改的

**Comment by NN708** [comment]
应该是做完了
