### ISSUE TITLE
SmoothScroll 存在回弹 bug

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#17]
不知道什么原因，当滚动条处于文档较上位置时，鼠标按住它下拉并停在某个位置后会发生回弹。此时一旦微动鼠标会立即引起滚动条更新，但是鼠标一旦停下即会再次回弹。

**Comment by jjyyxx** [comment]
之前没有考虑到滚动条可以拖动的功能，之后将会修复。

**Comment by shigma** [comment]
@jjyyxx 额外增加一个问题：
当从文档其他页面，再切回文档时，会发生从上至下的滚动，希望能够避免这种现象。

**Comment by jjyyxx** [comment]
之后会系统地区分平滑滚动与直接定位，应当能解决这一问题

**Comment by jjyyxx** [comment]
`SmoothScroll`已经进行了改善，从底层已经能解决文档的回弹以及直接定位问题。回弹现象从我测试来看已经解决，直接定位还没有与documents.js内对`SmoothScroll`的API的调用整合，有需要直接定位处只需要传入第二个参数false即可。
```javascript
scroll.scrollByDelta(100, false) // 应该不太会需要这样用
scroll.scrollByPosition(800, false)
```
