### ISSUE TITLE
主题系统的一些问题

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#19]
- [x] 切换主题时编辑器的颜色未能切换
- [x] 切换主题后文档的代码块部分颜色未能切换，且这个切换将被延后，即下一次切换主题后才切换到上一次的主题

**Comment by shigma** [comment]
目前当切换主题时，doc 和 editor 存在上色不一致的问题。即：editor 保留过去的上色，而 doc 则会切换到另外一种（未配置的）颜色上去。切回时主题再度相同。暂时难以理解其中的原因。@jjyyxx

**Comment by jjyyxx** [comment]
fixed
