### ISSUE TITLE
文档导航栏出现异常下划线

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#21]
![tim 20180623230501](https://user-images.githubusercontent.com/33423008/41811005-09c65850-773a-11e8-8013-9fd3824024aa.png)
如上图所示，鼠标悬浮于“语言概述”，但是“简单的语法”却也出现了下划线。
- 系统：Windows 10
- 分辨率：1920 * 1080
- 缩放：150%，在其他缩放比例下不可复现

**Comment by NN708** [comment]
复现中发现，此时“简单的语法”的 decoration 属性是 none 而不是 underline，因而这可能是一个渲染上的错误。

**Comment by jjyyxx** [comment]
经尝试，在思源字体下存在此问题，在Chrome+win10默认字体下无此问题，怀疑可能与字体有一定联系。 @NN708 你对字体这方面比较熟悉，能不能进行一下研究？
https://github.com/jjyyxx/vue-electron-repro 一个最简的可复现例子
