### ISSUE TITLE
标签页重叠时出现缺角现象

### ISSUE THREAD

**Issue by NN708** [obstudio/Thulium-Music-3#22]
如图

![default](https://user-images.githubusercontent.com/20534082/41816854-f15b9374-77c1-11e8-987d-85c3a79d0cf5.png)

**Comment by shigma** [comment]
这个是目前用 css 实现方法的硬伤，无法有效解决，除非使用 svg 或者其他填充手段。建议你来完成这个问题的处理。

**Comment by NN708** [comment]
f3da391：采用缩短 title，left-border、right-border 透明的方式初步解决，请查看是否有其它潜在的问题。 @Shigma
