### ISSUE TITLE
有关快速播放的几个问题

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#6]
- [x] 点击音轨所在的 CodeLens 并不会导致正常播放
- [x] 播放加载速度有点慢，应该考虑缓存或者优化
- [x] 播放时应该保证同时只有一个 TmPlayer 在工作
- [x] 开启多次播放以后会报错，从而不能继续播放
- [x] 关闭标签页时，如果播放是在该标签页下工作的，应停止播放

**Comment by jjyyxx** [comment]
初步分析如下：
1. 情况未知，可能是codelens对接问题
2. 现在是在线加载，近期会转变成本地加载
3. codelens与主逻辑没有有效整合
4. 没有妥善销毁或复用audioctx，导致数量超过上限
欢迎积极提供pr

**Comment by shigma** [comment]
加一个问题：关闭标签页时，希望如果播放是在该标签页下工作的，那么停止播放。（来自我的室友）

**Comment by NN708** [comment]
已全部修复。
