### ISSUE TITLE
编辑器区域显示奇怪的白线

### ISSUE THREAD

**Issue by shigma** [obstudio/Thulium-Music-3#8]
有电脑显示编辑界面打开时有一条奇怪的白线显示在标签栏下方。开启菜单栏后消失。如图。

![image1](https://user-images.githubusercontent.com/33423008/41545590-1be34f38-734e-11e8-9886-dd6fcda01e9e.png)
![image2](https://user-images.githubusercontent.com/33423008/41545588-1bb2087e-734e-11e8-8f21-6ce522ea6e30.png)

**Comment by jjyyxx** [comment]
能否提供出现该情况的电脑的操作系统、分辨率、缩放情况、当前窗口大小等信息? @Shigma

**Comment by shigma** [comment]
@jjyyxx 
操作系统：Windows 10
分辨率：1920*1080
窗口大小：任何情况下都有这种情况发生

**Comment by jjyyxx** [comment]
找了一个可能的原因，麻烦有空时看一下editor分支最新的code有没有修复问题。 @Shigma

**Comment by shigma** [comment]
已经修复。
