### ISSUE TITLE
Doc界面的几个问题

### ISSUE THREAD

**Issue by Track07-cda** [obstudio/Thulium-Music-3#9]
- [x] 切换Section时页面阅读进度未被重置至顶
- [x] Document的Dark与Simple主题相同
- [x] doc正文使用衬线字体
- [x] 最大化时目录栏特别宽

**Comment by shigma** [comment]
都是中肯的建议。会逐一进行处理。
PS：目录栏应该会重做。计划做成可以隐藏的样式，宽度在屏幕宽度较大时会设计成固定值。其中的内容也会更改。
